#!/usr/bin/env python3
"""
Builds source/src/data/shellNinjaLogo.ts: a small base64 PNG of assets/shell-ninja.png for use
in the Settings page footer logo. Run automatically by build_apk.sh; re-run any time you replace
assets/shell-ninja.png.
"""
import base64
from io import BytesIO
from pathlib import Path
from PIL import Image

here = Path(__file__).resolve().parent
src_path = here / "assets" / "shell-ninja.png"
out = here / "source" / "src" / "data" / "shellNinjaLogo.ts"

SIZE = 80  # small logo for the in-app footer; keeps the JS bundle small


def main():
    im = Image.open(src_path).convert("RGBA")
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)
    im.thumbnail((SIZE, SIZE), Image.LANCZOS)
    buf = BytesIO()
    im.save(buf, format="PNG", optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    out.write_text(
        "// Generated by embed_shell_ninja_logo.py from assets/shell-ninja.png. Do not edit by hand.\n"
        f'export const SHELL_NINJA_LOGO_URI = "data:image/png;base64,{b64}";\n',
        encoding="utf-8",
    )
    print(f"Embedded Shell Ninja logo into {out} ({len(b64)} base64 chars)")


if __name__ == "__main__":
    main()
