#!/usr/bin/env python3
"""
Builds source/src/data/appIcon.ts: a small base64 PNG of assets/app-icon-source.png for use in the
app's own header (the launcher icon itself is generated separately by generate_icons.py). Run
automatically by the build script; re-run any time you replace assets/app-icon-source.png.
"""
import base64
from io import BytesIO
from pathlib import Path
from PIL import Image

here = Path(__file__).resolve().parent
src_path = here / "assets" / "app-icon-source.png"
out = here / "source" / "src" / "data" / "appIcon.ts"

SIZE = 160  # plenty for any in-app header; keeps the JS bundle small


def main():
    im = Image.open(src_path).convert("RGBA")
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)
    im.thumbnail((SIZE, SIZE), Image.LANCZOS)
    buf = BytesIO()
    im.save(buf, format="PNG", optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    out.write_text(
        "// Generated by embed_icon.py from assets/app-icon-source.png. Do not edit by hand.\n"
        f'export const APP_ICON_DATA_URI = "data:image/png;base64,{b64}";\n',
        encoding="utf-8",
    )
    print(f"Embedded app icon into {out} ({len(b64)} base64 chars)")


if __name__ == "__main__":
    main()
