#!/usr/bin/env python3
"""
Builds source/src/data/userLists.ts from two files (run automatically by the build script):
  blocklists/block-list.md  - the structured list (## Top-Level Domains / Keywords / Domains sections,
                               each a fenced code block; keyword lines are prefixed "kw:")
  blocklists/my_list.txt    - your own quick additions, one plain domain or keyword per line
  blocklists/whitelist.txt  - words/phrases that should never be blocked, one per line
Re-run any time you edit those files; the app picks up the result on the next build.
"""
import json
import re
from pathlib import Path

here = Path(__file__).resolve().parent
out = here / "source" / "src" / "data" / "userLists.ts"

DOMAIN_LINE = re.compile(r"^[a-z0-9]([a-z0-9_-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9_-]*[a-z0-9])?)+$")
SIMPLE_DOMAIN = re.compile(r"^(?:[a-z][a-z0-9+.-]*://)?(?:www\.)?([a-z0-9-]+(?:\.[a-z0-9-]+)+)(?:[/?:].*)?$")


def parse_structured(path: Path):
    """Parses the '## N. Section' + fenced-code-block format described in blocklists/block-list.md.
    Supports both plaintext and encrypted/compressed (zlib+base64) formats."""
    import base64
    import zlib
    domains, keywords, tlds = [], [], []
    if not path.exists():
        return domains, keywords, tlds
    section = None
    in_fence = False
    raw_content = path.read_text(encoding="utf-8", errors="ignore")
    # Check if the file is encrypted/obfuscated (supports nested encryption)
    while True:
        enc_match = re.search(r"```encrypted-blocklist\s*([A-Za-z0-9+/=\s]+)\s*```", raw_content)
        if not enc_match:
            break
        try:
            b64_data = "".join(enc_match.group(1).split())
            raw_content = zlib.decompress(base64.b64decode(b64_data)).decode("utf-8")
        except Exception as e:
            print(f"Warning: could not decrypt blocklist: {e}")
            break
    for raw in raw_content.splitlines():
        line = raw.strip()
        header = re.match(r"^#{1,6}\s*\d*\.?\s*(.+)$", line)
        if header and not in_fence:
            h = header.group(1).lower()
            if "top-level domain" in h or "tld" in h:
                section = "tld"
            elif "keyword" in h:
                section = "keyword"
            elif "domain" in h:
                section = "domain"
            continue
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if not in_fence or not line or section is None:
            continue
        low = line.lower()
        if section == "tld":
            if low.startswith("."):
                tlds.append(low)
        elif section == "keyword":
            if low.startswith("kw:"):
                keywords.append(low[3:].strip())
        elif section == "domain":
            candidate = low[4:] if low.startswith("kw:") else low
            if low.startswith("."):
                tlds.append(low)
            elif DOMAIN_LINE.match(candidate):
                domains.append(candidate)
            # anything else (stray "---" separators, blank noise, etc.) is silently skipped
    return domains, keywords, tlds


def parse_simple(path: Path):
    """Parses a plain one-entry-per-line file: a domain-looking line is a website, anything else a keyword."""
    domains, keywords = [], []
    if not path.exists():
        return domains, keywords
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = re.sub(r"\s+#.*$", "", raw).strip().lower()
        if not line or line.startswith("#"):
            continue
        m = SIMPLE_DOMAIN.match(line)
        if m and " " not in line:
            domains.append(m.group(1))
        else:
            keywords.append(re.sub(r"\s+", " ", line))
    return domains, keywords


def parse_whitelist(path: Path):
    if not path.exists():
        return []
    out = []
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = re.sub(r"\s+#.*$", "", raw).strip().lower()
        if line and not line.startswith("#"):
            out.append(re.sub(r"\s+", " ", line))
    return out


d1, k1, tlds = parse_structured(here / "blocklists" / "block-list.md")
d2, k2 = parse_simple(here / "blocklists" / "my_list.txt")
whitelist = parse_whitelist(here / "blocklists" / "whitelist.txt")

domains = sorted(set(d1 + d2))
keywords = sorted(set(k1 + k2))
tlds = sorted(set(tlds))
whitelist = sorted(set(whitelist))

out.write_text(
    "// Generated by import_lists.py from blocklists/block-list.md, my_list.txt and whitelist.txt. "
    "Do not edit by hand.\n"
    f"export const USER_DOMAINS: string[] = {json.dumps(domains, ensure_ascii=False)};\n"
    f"export const USER_KEYWORDS: string[] = {json.dumps(keywords, ensure_ascii=False)};\n"
    f"export const USER_TLDS: string[] = {json.dumps(tlds, ensure_ascii=False)};\n"
    f"export const USER_DEFAULT_WHITELIST: string[] = {json.dumps(whitelist, ensure_ascii=False)};\n",
    encoding="utf-8",
)
print(
    f"Imported {len(domains)} websites, {len(keywords)} keywords, {len(tlds)} TLDs, "
    f"{len(whitelist)} whitelist phrases"
)
