#!/usr/bin/env python3
"""
Reads/writes VERSION and .build_number, and generates source/src/data/appVersion.ts so the app
can show its own version. Run automatically by build_apk.sh before every build.

- VERSION holds the marketing version (e.g. "1.2.0"). Edit it by hand whenever you want to bump
  it, or set APP_VERSION=1.2.0 as an environment variable for a single build:
      APP_VERSION=1.2.0 ./build_apk.sh release
- .build_number is an internal counter that goes up by 1 on every single build (debug or
  release). Don't edit it by hand \u2014 it exists so two installs of the same VERSION are still
  distinguishable, and so Android always sees a build as "newer" than the last one installed.
"""
import os
from pathlib import Path

here = Path(__file__).resolve().parent
version_file = here / "VERSION"
build_file = here / ".build_number"
out = here / "source" / "src" / "data" / "appVersion.ts"

version = os.environ.get("APP_VERSION", "").strip()
if not version:
    version = version_file.read_text(encoding="utf-8").strip() if version_file.exists() else "1.0.0"
version_file.write_text(version + "\n", encoding="utf-8")

build_number = 0
if build_file.exists():
    try:
        build_number = int(build_file.read_text(encoding="utf-8").strip())
    except ValueError:
        build_number = 0
build_number += 1
build_file.write_text(str(build_number) + "\n", encoding="utf-8")

out.write_text(
    "// Generated by set_version.py from VERSION and .build_number. Do not edit by hand.\n"
    f'export const APP_VERSION = "{version}";\n'
    f"export const BUILD_NUMBER = {build_number};\n",
    encoding="utf-8",
)
print(f"Version {version} (build {build_number})")
