// Generated by import_lists.py from blocklists/block-list.md, my_list.txt and whitelist.txt. Do not edit by hand.
export const USER_DOMAINS: string[] = [];
export const USER_KEYWORDS: string[] = [];
export const USER_TLDS: string[] = [];
export const USER_DEFAULT_WHITELIST: string[] = ["adult education", "adulteducation", "camera", "essex", "sex ed", "sex education", "sussex", "wessex"];
